on: [push, pull_request]
jobs:
    openapi_check:
      name: "OpenAPI check"
      runs-on: ubuntu-latest
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - name: "Generate deutschland code"
          uses: wirthual/deutschland-generator-action@v0.1.5
          with:
            version: 1.0.1
            package-name: "autobahn"
            openapi-file: ${{ github.workspace }}/openapi.yaml