on: [push, pull_request]
jobs:
    openapi_check:
      name: "OpenAPI check"
      runs-on: ubuntu-latest
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - name: Checkout
          uses: actions/checkout@v2

        - name: Print dir
          run: |
            ls ${{ github.workspace }}

        # Runs a single command using the runners shell
        - name: Check if file is correct
          uses: stoplightio/spectral-action@v0.8.1
          with:
            file_glob: openapi.yaml

        - name: Generate Python Client
          uses: openapi-generators/openapitools-generator-action@v1
          with:
            generator: python
            openapi-file: openapi.yaml
